export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const FIND_SHOW_BY_ID = "FIND_SHOW_BY_ID";
export const FIND_TRENDING_SHOWS = "FIND_TRENDING_SHOWS";

export const FILTER_SINGLE_PAGE = "FILTER_SINGLE_PAGE";

export const SHOW_PREVIOUS_RESULTS = "SHOW_PREVIOUS_RESULTS";



export const SHOW_SINGLE_PAGE = "SHOW_SINGLE_PAGHE";