export const REQUEST_SEARCH_RESULTS = "REQUEST_SEARCH_RESULTS";

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SET_SHOW_BY_ID = "SET_SHOW_BY_ID";

export const GET_TRENDING_SHOWS = "GET_TRENDING_SHOWS";
export const SET_TRENDING_SHOWS = "SET_TRENDING_SHOWS";

export const SET_SHOWS_BY_GENRE = "SET_SHOWS_BY_GENRE";

export const FILTER_SINGLE_PAGE = "FILTER_SINGLE_PAGE";

export const SHOW_PREVIOUS_RESULTS = "SHOW_PREVIOUS_RESULTS";

export const GET_EXTRA_SHOW_INFO = "GET_EXTRA_SHOW_INFO";
export const SET_EXTRA_SHOW_INFO = "SET_EXTRA_SHOW_INFO";
export const SET_EXTRA_PROFILE_INFO = "SET_EXTRA_PROFILE_INFO";

export const SHOW_SINGLE_PAGE = "SHOW_SINGLE_PAGHE";

export const TOGGLE_BOOKMARKS = "TOGGLE_BOOKMARKS"
export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const SET_BOOKMARKS_STORAGE = "SET_BOOKMARKS_STORAGE";
export const UPDATE_BOOKMARKS_STORAGE = "UPDATE_BOOKMARKS_STORAGE";

export const GET_SEARCH_SUGGESTIONS = "GET_SEARCH_SUGGESTIONS";
export const SET_SEARCH_SUGGESTIONS = "SET_SEARCH_SUGGESTIONS";
export const FOCUS_OUT_SEARCH_SUGEGSTIONS = "FOCUS_OUT_SEARCH_SUGEGSTIONS";
export const DELETE_SEARCH_SUGGESTIONS_INPUT  = "DELETE_SEARCH_SUGGESTIONS_INPUT";
export const SET_SEARCH_SUGGESTIONS_TIMEOUT = "SET_SEARCH_SUGGESTIONS_TIMEOUT";
export const CLEAR_SEARCH_SUGGESTIONS_TIMEOUT = "CLEAR_SEARCH_SUGGESTIONS_TIMEOUT";