import * as actions from "./trendingShowsActions";
import { SET_TRENDING_SHOWS } from "../../actionTypes/actionTypes";
import configureMockStore from "redux-mock-store";
import thunk from "redux-thunk";

const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

describe("showByIdActions", () => {
  let store;
  beforeEach(() => {
    store = mockStore({});
  });

  it("should create action to SET_TRENDING_SHOWS", () => {
    const searchResults = [
      {
        original_name: "La casa de papel",
        id: 71446,
        name: "Money Heist",
        vote_count: 5066,
        vote_average: 8.5,
        first_air_date: "2017-05-02",
        poster_path: "/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
        genre_ids: [80, 18],
        original_language: "es",
        backdrop_path: "/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
        overview:
          "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
        origin_country: ["ES"],
        popularity: 163.567,
        media_type: "tv",
      },
      {
        id: 38700,
        video: false,
        vote_count: 3149,
        vote_average: 7.2,
        title: "Bad Boys for Life",
        release_date: "2020-01-15",
        original_language: "en",
        original_title: "Bad Boys for Life",
        genre_ids: [28, 80, 53],
        backdrop_path: "/upUy2QhMZEmtypPW3PdieKLAHxh.jpg",
        adult: false,
        overview:
          "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
        poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
        popularity: 199.966,
        media_type: "movie",
      },
      {
        id: 181812,
        video: false,
        vote_count: 4032,
        vote_average: 6.5,
        title: "Star Wars: The Rise of Skywalker",
        release_date: "2019-12-18",
        original_language: "en",
        original_title: "Star Wars: The Rise of Skywalker",
        genre_ids: [28, 12, 878],
        backdrop_path: "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
        adult: false,
        overview:
          "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
        poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
        popularity: 177.42,
        media_type: "movie",
      },
      {
        id: 443791,
        video: false,
        vote_count: 763,
        vote_average: 6.5,
        title: "Underwater",
        release_date: "2020-01-08",
        original_language: "en",
        original_title: "Underwater",
        genre_ids: [28, 27, 878, 53],
        backdrop_path: "/fYPiQewg7ogbzro2XcCTACSB2KC.jpg",
        adult: false,
        overview:
          "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
        poster_path: "/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg",
        popularity: 197.583,
        media_type: "movie",
      },
      {
        id: 495764,
        video: false,
        vote_count: 3071,
        vote_average: 7.2,
        title:
          "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
        release_date: "2020-02-05",
        original_language: "en",
        original_title:
          "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
        genre_ids: [28, 35, 80],
        backdrop_path: "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
        adult: false,
        overview:
          "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
        poster_path: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
        popularity: 165.043,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
        genre_ids: [28, 878, 35, 10751],
        id: 454626,
        original_language: "en",
        original_title: "Sonic the Hedgehog",
        overview:
          "Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
        poster_path: "/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
        release_date: "2020-02-12",
        title: "Sonic the Hedgehog",
        video: false,
        vote_average: 7.6,
        vote_count: 2818,
        popularity: 213.873,
        media_type: "movie",
      },
      {
        id: 512200,
        video: false,
        vote_count: 3250,
        vote_average: 6.9,
        title: "Jumanji: The Next Level",
        release_date: "2019-12-04",
        original_language: "en",
        original_title: "Jumanji: The Next Level",
        genre_ids: [12, 35, 14],
        backdrop_path: "/oLma4sWjqlXVr0E3jpaXQCytuG9.jpg",
        adult: false,
        overview:
          "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
        poster_path: "/bB42KDdfWkOvmzmYkmK58ZlCa9P.jpg",
        popularity: 139.953,
        media_type: "movie",
      },
      {
        id: 338762,
        video: false,
        vote_count: 1700,
        vote_average: 7.2,
        title: "Bloodshot",
        release_date: "2020-03-05",
        original_language: "en",
        original_title: "Bloodshot",
        genre_ids: [28, 878],
        backdrop_path: "/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg",
        adult: false,
        overview:
          "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
        poster_path: "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
        popularity: 168.784,
        media_type: "movie",
      },
      {
        id: 446893,
        video: false,
        vote_count: 275,
        vote_average: 7.8,
        title: "Trolls World Tour",
        release_date: "2020-03-12",
        original_language: "en",
        original_title: "Trolls World Tour",
        genre_ids: [12, 16, 35, 14, 10402, 10751],
        backdrop_path: "/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg",
        adult: false,
        overview:
          "Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.",
        poster_path: "/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg",
        popularity: 199.564,
        media_type: "movie",
      },
      {
        id: 522627,
        video: false,
        vote_count: 906,
        vote_average: 7.8,
        title: "The Gentlemen",
        release_date: "2020-01-01",
        original_language: "en",
        original_title: "The Gentlemen",
        genre_ids: [28, 35, 80],
        backdrop_path: "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
        adult: false,
        overview:
          "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
        poster_path: "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
        popularity: 120.519,
        media_type: "movie",
      },
      {
        id: 539537,
        video: false,
        vote_count: 277,
        vote_average: 5.4,
        title: "Fantasy Island",
        release_date: "2020-02-12",
        original_language: "en",
        original_title: "Fantasy Island",
        genre_ids: [14, 27, 878],
        backdrop_path: "/x80ZIVGUJ6plcUBcgVZ6DPKT7vc.jpg",
        adult: false,
        overview:
          "A group of contest winners arrive at an island hotel to live out their dreams, only to find themselves trapped in nightmare scenarios.",
        poster_path: "/rbrvkNWDyF1NKzvAlIHepFBSBJq.jpg",
        popularity: 147.592,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/vw3zNfzvnVNF7nIjpiEgcdznfeC.jpg",
        genre_ids: [14, 28, 12, 16],
        id: 664767,
        original_language: "en",
        original_title: "Mortal Kombat Legends: Scorpions Revenge",
        overview:
          "After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.",
        poster_path: "/iBvo3qOPcmhlqAaJcXcQHtx2qLk.jpg",
        release_date: "2020-04-12",
        title: "Mortal Kombat Legends: Scorpion’s Revenge",
        video: false,
        vote_average: 8.5,
        vote_count: 123,
        popularity: 201.782,
        media_type: "movie",
      },
      {
        id: 508439,
        video: false,
        vote_count: 1251,
        vote_average: 8,
        title: "Onward",
        release_date: "2020-02-29",
        original_language: "en",
        original_title: "Onward",
        genre_ids: [12, 16, 35, 14, 10751],
        backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
        adult: false,
        overview:
          "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
        poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
        popularity: 140.588,
        media_type: "movie",
      },
      {
        id: 448119,
        video: false,
        vote_count: 1209,
        vote_average: 6.8,
        title: "Dolittle",
        release_date: "2020-01-01",
        original_language: "en",
        original_title: "Dolittle",
        genre_ids: [12, 35, 14, 10751],
        backdrop_path: "/xcUf6yIheo78btFqihlRLftdR3M.jpg",
        adult: false,
        overview:
          "After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.",
        poster_path: "/xnjvwfDulnOCy8qtYX0iqydmMhk.jpg",
        popularity: 66.909,
        media_type: "movie",
      },
      {
        id: 330457,
        video: false,
        vote_count: 3904,
        vote_average: 7.2,
        title: "Frozen II",
        release_date: "2019-11-20",
        original_language: "en",
        original_title: "Frozen II",
        genre_ids: [12, 16, 10751],
        backdrop_path: "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
        adult: false,
        overview:
          "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
        poster_path: "/h6Wi81XNXCjTAcdstiCLRykN3Pa.jpg",
        popularity: 77.484,
        media_type: "movie",
      },
      {
        id: 570670,
        video: false,
        vote_count: 1498,
        vote_average: 7.2,
        title: "The Invisible Man",
        release_date: "2020-02-26",
        original_language: "en",
        original_title: "The Invisible Man",
        genre_ids: [27, 878, 53],
        backdrop_path: "/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg",
        adult: false,
        overview:
          "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
        poster_path: "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
        popularity: 89.854,
        media_type: "movie",
      },
      {
        id: 466622,
        video: false,
        vote_count: 69,
        vote_average: 5.6,
        title: "The Rhythm Section",
        release_date: "2020-01-31",
        original_language: "en",
        original_title: "The Rhythm Section",
        genre_ids: [28, 53],
        backdrop_path: "/xpBTeAtDqd7sbXUS64dSILIPwtJ.jpg",
        adult: false,
        overview:
          "After the death of her family in an airplane crash on a flight that she was meant to be on, Stephanie Patrick discovers the crash was not an accident. She then seeks to uncover the truth by adapting the identity of an assassin to track down those responsible.",
        poster_path: "/jjLcdF5ZLWHho96jTbUrJCpzztD.jpg",
        popularity: 134.694,
        media_type: "movie",
      },
      {
        id: 526019,
        video: false,
        vote_count: 159,
        vote_average: 6.6,
        title: "Like a Boss",
        release_date: "2020-01-09",
        original_language: "en",
        original_title: "Like a Boss",
        genre_ids: [35],
        backdrop_path: "/wMv7GL12s0bJmfv3ckdglOCQ8B3.jpg",
        adult: false,
        overview:
          "Two female friends with very different ideals decide to start a beauty company together. One is more practical, while the other wants to earn her fortune and live a lavish lifestyle.",
        poster_path: "/ifn7yLH7W69MdrEEkNzCyO8rTmL.jpg",
        popularity: 68.778,
        media_type: "movie",
      },
      {
        id: 530915,
        video: false,
        vote_count: 4299,
        vote_average: 7.9,
        title: "1917",
        release_date: "2019-12-25",
        original_language: "en",
        original_title: "1917",
        genre_ids: [28, 18, 53, 10752],
        backdrop_path: "/2WgieNR1tGHlpJUsolbVzbUbE1O.jpg",
        adult: false,
        overview:
          "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
        poster_path: "/AuGiPiGMYMkSosOJ3BQjDEAiwtO.jpg",
        popularity: 79.679,
        media_type: "movie",
      },
      {
        id: 592834,
        video: false,
        vote_count: 103,
        vote_average: 7.2,
        title: "My Spy",
        release_date: "2020-02-27",
        original_language: "en",
        original_title: "My Spy",
        genre_ids: [28, 35, 10751],
        backdrop_path: "/yalJdTsb6EcDX5devj2ltWXuceO.jpg",
        adult: false,
        overview:
          "A hardened CIA operative finds himself at the mercy of a precocious 9-year-old girl, having been sent undercover to surveil her family.",
        poster_path: "/n2C6jRK9PtPIs99RQhKtqGlsnsO.jpg",
        popularity: 106.165,
        media_type: "movie",
      },
    ];
    const expectedOutput = [
      {
        type: SET_TRENDING_SHOWS,
        payload: {
          searchResults,
        },
      },
    ];

    store.dispatch(actions.setTrendingShows(searchResults));
    return expect(store.getActions()).toEqual(expectedOutput);
  });
});
