import * as actions from "./extraProfileInfoActions";
import { SET_EXTRA_PROFILE_INFO } from "../../actionTypes/actionTypes";
import configureMockStore from "redux-mock-store";
import thunk from "redux-thunk";

actions.getExtraProfileInfo = jest.fn(() => {
  return {
    type: SET_EXTRA_PROFILE_INFO,
  };
});

const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

describe("extraProfileInfoActions", () => {
  let store;
  beforeEach(() => {
    store = mockStore({});
  });

  it("should create action to SET_EXTRA_PROFILE_INFO if getExtraProfileInfo is called", () => {
    const expectedOutput = [{ type: SET_EXTRA_PROFILE_INFO }];

    store.dispatch(actions.getExtraProfileInfo());
    return expect(store.getActions()).toEqual(expectedOutput);
  });
  it("should create action to SET_EXTRA_PROFILE_INFO if setExtraProfileInfo is called", () => {
    const profileDetails = {
      birthday: "1996-02-21",
      known_for_department: "Acting",
      deathday: null,
      id: 1001657,
      name: "Sophie Turner",
      also_known_as: ["소피 터너", "Σόφι Τέρνερ", "Софи Тёрнер"],
      gender: 1,
      biography:
        "Sophie Turner (born 21 February 1996) is an English actress. Turner made her professional acting debut as Sansa Stark on the HBO fantasy television series Game of Thrones (2011–2019), which brought her international recognition.\n\nTurner has also starred in the television film The Thirteenth Tale (2013) and she made her feature film debut in Another Me (2013). She has also starred in the action comedy Barely Lethal (2015) and portrays a young Jean Grey / Phoenix in the X-Men film series.",
      popularity: 5.409,
      place_of_birth: "Northampton, Northamptonshire, England",
      profile_path: "/5lzG6z74a8aYVWLsoAQVkyh5IEa.jpg",
      adult: false,
      imdb_id: "nm3849842",
      homepage: null,
    };
    const profileCredits = [
      {
        id: 414187,
        character: "Josie",
        original_title: "Josie",
        overview:
          "Everyone knows everyone in the southern town of Baymont. So when tattooed, sweet-talking Josie struts into town, heads turn. Striking up relationships with young punk Gator and loner Hank, she quickly becomes a hot topic of local gossip.",
        vote_count: 37,
        video: false,
        media_type: "movie",
        poster_path: "/sXwATbG3eJjkteGh1YaqV1PGeGb.jpg",
        backdrop_path: "/mnyiidfEfSBIHDcsnoIVNNjXuZH.jpg",
        popularity: 4.877,
        title: "Josie",
        original_language: "en",
        genre_ids: [18, 53],
        vote_average: 5.3,
        adult: false,
        release_date: "2018-03-16",
        credit_id: "57ccc0ea92514151990008be",
      },
      {
        id: 252529,
        character: "Fay Delussey / Lila Delussey",
        original_title: "Another Me",
        overview:
          "A teenager finds her perfect life upended when she's stalked by a mysterious doppelganger who has her eyes set on assuming her identity.",
        vote_count: 131,
        video: false,
        media_type: "movie",
        poster_path: "/ryGdE6W9oMSKSRE0CSaHActo4oh.jpg",
        backdrop_path: "/p30zjdch82XjnUjNdTgbcxt60gG.jpg",
        popularity: 5.99,
        title: "Another Me",
        original_language: "en",
        genre_ids: [18, 27, 9648, 53],
        vote_average: 4.9,
        adult: false,
        release_date: "2013-11-15",
        credit_id: "535bd09fc3a36830840016b0",
      },
      {
        id: 248574,
        character: "Heather",
        original_title: "Barely Lethal",
        overview:
          'A 16-year-old international assassin yearning for a "normal" adolescence fakes her own death and enrolls as a senior in a suburban high school. She quickly learns that being popular can be more painful than getting water-boarded.',
        vote_count: 667,
        video: false,
        media_type: "movie",
        poster_path: "/uWJ3suK86L8PGpNxZEIRIKPMx0S.jpg",
        backdrop_path: null,
        popularity: 11.098,
        title: "Barely Lethal",
        original_language: "en",
        genre_ids: [28, 12, 35],
        vote_average: 5.7,
        adult: false,
        release_date: "2015-04-30",
        credit_id: "52fe4f35c3a36847f82c5561",
      },
      {
        popularity: 0.942,
        character: "Penelope",
        credit_id: "55504ee9c3a3682254005fff",
        vote_count: 0,
        video: false,
        media_type: "movie",
        original_language: "en",
        vote_average: 0,
        id: 339754,
        title: "Broken Soldier",
        original_title: "Broken Soldier",
        backdrop_path: null,
        genre_ids: [18],
        adult: false,
        overview: "A war veteran suffering from PTSD befriends a teenage girl.",
        poster_path: null,
      },
      {
        id: 451925,
        character: "Debbie",
        original_title: "Time Freak",
        overview:
          "Stillman, a heartbroken physics student, builds a time machine when his girlfriend breaks up with him. Going back in time, he attempts to save their relationship by fixing every mistake he made—while dragging his best friend along in the process.",
        vote_count: 155,
        video: false,
        media_type: "movie",
        poster_path: "/17FFyw0tmwuLailIWVYFHaRLZWJ.jpg",
        backdrop_path: "/90Vk1RuNt5hdufI0J1IGDRfx9S6.jpg",
        popularity: 7.685,
        title: "Time Freak",
        original_language: "en",
        genre_ids: [35, 878, 10749],
        vote_average: 6.3,
        adult: false,
        release_date: "2018-11-09",
        credit_id: "58ef1f6792514141fb008459",
      },
      {
        id: 513487,
        character: "Maddie",
        original_title: "Heavy",
        overview:
          "Revenge thriller set in New York centers on a crazy couple living it up in the high-end drugs scene.",
        vote_count: 2,
        video: false,
        media_type: "movie",
        release_date: "2019-09-07",
        vote_average: 0,
        title: "Heavy",
        popularity: 1.297,
        original_language: "en",
        genre_ids: [18, 10749],
        backdrop_path: null,
        adult: false,
        poster_path: null,
        credit_id: "5ab4a17fc3a3686173018081",
      },
      {
        id: 492606,
        character: "Sansa Stark (voice)",
        original_title: "Game of Thrones: Conquest & Rebellion",
        overview:
          "HBO's animated history of Westeros brings to life all the events that shaped the Seven Kingdoms in the thousands of years before Game of Thrones' story begins.",
        vote_count: 48,
        video: false,
        media_type: "movie",
        poster_path: "/b3HXxFnhy0pamuDY9rqJ4mk7L1t.jpg",
        backdrop_path: "/masCZracUmRKVDFovPoFo9ePNry.jpg",
        popularity: 9.537,
        title: "Game of Thrones: Conquest & Rebellion",
        original_language: "en",
        genre_ids: [16, 14, 10752, 10770],
        vote_average: 8,
        adult: false,
        release_date: "2017-12-12",
        credit_id: "5a362298c3a368148f0469a6",
      },
      {
        id: 320288,
        character: "Jean Grey / Dark Phoenix",
        original_title: "Dark Phoenix",
        overview:
          "The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.",
        vote_count: 3241,
        video: false,
        media_type: "movie",
        poster_path: "/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
        backdrop_path: "/cjRUhKyt2Jo3V1KNzc5tpPNfccG.jpg",
        popularity: 52.754,
        title: "Dark Phoenix",
        original_language: "en",
        genre_ids: [28, 12, 878],
        vote_average: 6,
        adult: false,
        release_date: "2019-06-05",
        credit_id: "589f3c3bc3a3684bc4010578",
      },
      {
        id: 601169,
        character: "Herself",
        original_title: "Chasing Happiness",
        overview:
          "From humble roots as pastor's sons in New Jersey, through their meteoric rise to fame, the Jonas Brothers' bond was unshakeable-until a surprising and painful breakup led Joe, Kevin and Nick down very different paths. With deeply personal interviews, previously unreleased footage and exclusive music, this is the Jonas Brothers as never seen before.",
        vote_count: 70,
        video: false,
        media_type: "movie",
        release_date: "2019-06-04",
        vote_average: 8.3,
        title: "Chasing Happiness",
        popularity: 8.116,
        original_language: "en",
        genre_ids: [99, 10402],
        backdrop_path: "/rIfbCaS9b9vOSIud2Fp3zXKO78g.jpg",
        adult: false,
        poster_path: "/feibieH87B0bwIBeKTwcXMx92sY.jpg",
        credit_id: "5cf62c960e0a260858ca14d4",
      },
      {
        id: 242409,
        character: "Young Adeline / Vida",
        original_title: "The Thirteenth Tale",
        overview:
          "Biographer Margaret Lea travels to the isolated rural mansion of the famous writer Vida Winter, who asks her to write her biography. Although initially she is reluctant, as Vida is known for constantly distorting the facts of her life, Margaret soon becomes fascinated with the story of a dark childhood, a disturbing tale that leads her to finally confront the traumas of her own past.",
        vote_count: 28,
        video: false,
        media_type: "movie",
        poster_path: "/o3lWdFzIPFaNkwCDszhmmJ4d8LE.jpg",
        backdrop_path: "/aHzJY3QgtlzZytFCHN3ETHXsfFJ.jpg",
        popularity: 5.462,
        title: "The Thirteenth Tale",
        original_language: "en",
        genre_ids: [18, 9648, 10770],
        vote_average: 6.4,
        adult: false,
        release_date: "2013-12-30",
        credit_id: "52fe4eccc3a36847f82a895d",
      },
      {
        id: 591278,
        character: "Herself",
        original_title: "Game of Thrones: The Last Watch",
        overview:
          "Post-finale feature-length documentary about the making-of the hit HBO TV show.",
        vote_count: 178,
        video: false,
        media_type: "movie",
        poster_path: "/tVyKpOYDtKzs4SOYCbZn4YNFWHI.jpg",
        backdrop_path: "/6hfmHRaZNKzazyDDLli5CbT6L8H.jpg",
        popularity: 12.936,
        title: "Game of Thrones: The Last Watch",
        original_language: "en",
        genre_ids: [99, 10770],
        vote_average: 7.1,
        adult: false,
        release_date: "2019-05-26",
        credit_id: "5cdf96d1c3a36819041e0fee",
      },
      {
        id: 246655,
        character: "Jean Grey / Phoenix",
        original_title: "X-Men: Apocalypse",
        overview:
          "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
        vote_count: 9287,
        video: false,
        media_type: "movie",
        poster_path: "/qttNmCib9gHhR5q0QoZ3FgmGom9.jpg",
        backdrop_path: "/2ex2beZ4ssMeOduLD0ILzXKCiep.jpg",
        popularity: 27.031,
        title: "X-Men: Apocalypse",
        original_language: "en",
        genre_ids: [28, 12, 14, 878],
        vote_average: 6.5,
        adult: false,
        release_date: "2016-05-18",
        credit_id: "54c28961c3a36878d0004106",
      },
      {
        id: 447167,
        character: "Herself",
        original_title: "X-Men: Apocalypse Unearthed",
        overview:
          "A six-part documentary. We get info about examines story/character areas and connections to other movies, cast and performances, costumes, makeup and effects, stunts/action, production design and photography, and general thoughts.",
        vote_count: 17,
        video: true,
        media_type: "movie",
        poster_path: "/paYCYNqtXYIwPcw85IpMvfzulc9.jpg",
        backdrop_path: null,
        popularity: 3.03,
        title: "X-Men: Apocalypse Unearthed",
        original_language: "en",
        genre_ids: [99],
        vote_average: 6.6,
        adult: false,
        release_date: "2016-11-04",
        credit_id: "58c994ec9251415e8d00185a",
      },
      {
        id: 1399,
        character: "Sansa Stark",
        episode_count: 73,
        overview:
          "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        origin_country: ["US"],
        original_name: "Game of Thrones",
        genre_ids: [18, 10765],
        name: "Game of Thrones",
        media_type: "tv",
        backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        popularity: 82.472,
        first_air_date: "2011-04-17",
        original_language: "en",
        vote_count: 7706,
        vote_average: 8.2,
        poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
        credit_id: "5256c8b419c2956ff6047f34",
      },
      {
        id: 72610,
        character: "Herself",
        episode_count: 1,
        overview:
          "Celebrity pairings ride along in a car together as they sing tunes from their personal playlists and surprise fans who don’t expect to see big stars belting out tunes one lane over. Based on the segment on The Late Late Show with James Corden.",
        origin_country: ["US"],
        original_name: "Carpool Karaoke",
        genre_ids: [35],
        name: "Carpool Karaoke",
        media_type: "tv",
        backdrop_path: "/lJSojr9b2KaddW1QI8q2bY6OXy.jpg",
        popularity: 5.376,
        first_air_date: "2017-08-08",
        original_language: "en",
        vote_count: 9,
        vote_average: 5.1,
        poster_path: "/bA6tpDMoyQO8fRmXC8sHh7LQoqW.jpg",
        credit_id: "599a59999251414a1800c327",
      },
      {
        id: 1220,
        character: "Herself",
        episode_count: 1,
        overview:
          "Each week celebrity guests join Irish comedian Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
        origin_country: ["GB"],
        original_name: "The Graham Norton Show",
        genre_ids: [35, 10767],
        name: "The Graham Norton Show",
        media_type: "tv",
        backdrop_path: "/2pJYis3LUEgFC3UErTQVgmUV1hN.jpg",
        popularity: 31.165,
        first_air_date: "2007-02-22",
        original_language: "en",
        vote_count: 126,
        vote_average: 7,
        poster_path: "/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg",
        credit_id: "5de894fa7646fd00159acd3a",
      },
      {
        id: 99248,
        character: "Jane",
        episode_count: 7,
        overview:
          "Jane's plane crashes on a remote snow-covered mountain and she, along with Paul, the only remaining survivors, must pull themselves out of the wreckage and fight for their lives. Together they embark on a harrowing journey out of the wilderness, battling brutal conditions and personal traumas.",
        origin_country: ["US"],
        original_name: "Survive",
        genre_ids: [],
        name: "Survive",
        media_type: "tv",
        backdrop_path: "/A9h3YUFbnQ7ReXwvnaQvJf5uNjC.jpg",
        popularity: 5.844,
        first_air_date: "2020-04-06",
        original_language: "en",
        vote_count: 1,
        vote_average: 1,
        poster_path: "/rMsM9Kzfw8ZTtYx6LF1GXNv8BOQ.jpg",
        credit_id: "5e4204fc0c2710001a818d2b",
      },
    ];

    const expectedOutput = [
      {
        type: SET_EXTRA_PROFILE_INFO,
        payload: {
          profileDetails,
          profileCredits,
        },
      },
    ];

    store.dispatch(actions.setExtraProfileInfo(profileDetails, profileCredits));
    return expect(store.getActions()).toEqual(expectedOutput);
  });
});
